import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Creative Posts",
  description: "Generated by create next app",
  icons: {
    icon: "/crl.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
          <html lang="en">
            <body>
              <Navbar />
              <main className="pt-[70px]">
                {children}
                <Toaster position="top-center" />
              </main>
            </body>
          </html>
  );
}
